{
  "build": "py312haa95532_0",
  "build_number": 0,
  "channel": "https://repo.anaconda.com/pkgs/main/win-64",
  "constrains": [
    "conda >=23.9.0"
  ],
  "depends": [
    "cryptography >=3.4.0",
    "keyring",
    "pkce",
    "pydantic",
    "pyjwt",
    "python >=3.12,<3.13.0a0",
    "python-dotenv",
    "requests",
    "semver <4"
  ],
  "extracted_package_dir": "E:\\SOFTWARE\\ANACONDA\\pkgs\\anaconda-cloud-auth-0.5.1-py312haa95532_0",
  "files": [
    "Lib/site-packages/anaconda_cloud_auth-0.5.1.dist-info/INSTALLER",
    "Lib/site-packages/anaconda_cloud_auth-0.5.1.dist-info/METADATA",
    "Lib/site-packages/anaconda_cloud_auth-0.5.1.dist-info/RECORD",
    "Lib/site-packages/anaconda_cloud_auth-0.5.1.dist-info/REQUESTED",
    "Lib/site-packages/anaconda_cloud_auth-0.5.1.dist-info/WHEEL",
    "Lib/site-packages/anaconda_cloud_auth-0.5.1.dist-info/direct_url.json",
    "Lib/site-packages/anaconda_cloud_auth-0.5.1.dist-info/entry_points.txt",
    "Lib/site-packages/anaconda_cloud_auth-0.5.1.dist-info/licenses/LICENSE",
    "Lib/site-packages/anaconda_cloud_auth/__init__.py",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/__init__.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/_version.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/actions.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/cli.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/client.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/config.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/console.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/exceptions.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/handlers.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/jwt.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/panel.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/__pycache__/token.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/_conda/__init__.py",
    "Lib/site-packages/anaconda_cloud_auth/_conda/__pycache__/__init__.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/_conda/__pycache__/auth_handler.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/_conda/__pycache__/entrypoint.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/_conda/__pycache__/plugins.cpython-312.pyc",
    "Lib/site-packages/anaconda_cloud_auth/_conda/auth_handler.py",
    "Lib/site-packages/anaconda_cloud_auth/_conda/entrypoint.py",
    "Lib/site-packages/anaconda_cloud_auth/_conda/plugins.py",
    "Lib/site-packages/anaconda_cloud_auth/_version.py",
    "Lib/site-packages/anaconda_cloud_auth/actions.py",
    "Lib/site-packages/anaconda_cloud_auth/cli.py",
    "Lib/site-packages/anaconda_cloud_auth/client.py",
    "Lib/site-packages/anaconda_cloud_auth/config.py",
    "Lib/site-packages/anaconda_cloud_auth/console.py",
    "Lib/site-packages/anaconda_cloud_auth/exceptions.py",
    "Lib/site-packages/anaconda_cloud_auth/handlers.py",
    "Lib/site-packages/anaconda_cloud_auth/jwt.py",
    "Lib/site-packages/anaconda_cloud_auth/panel.py",
    "Lib/site-packages/anaconda_cloud_auth/py.typed",
    "Lib/site-packages/anaconda_cloud_auth/token.py",
    ".nonadmin"
  ],
  "fn": "anaconda-cloud-auth-0.5.1-py312haa95532_0.conda",
  "license": "BSD-3-Clause",
  "link": {
    "source": "E:\\SOFTWARE\\ANACONDA\\pkgs\\anaconda-cloud-auth-0.5.1-py312haa95532_0",
    "type": 1
  },
  "md5": "ce2b46fb864fa7878e37daad5532b1f4",
  "name": "anaconda-cloud-auth",
  "package_tarball_full_path": "E:\\SOFTWARE\\ANACONDA\\pkgs\\anaconda-cloud-auth-0.5.1-py312haa95532_0.conda",
  "paths_data": {
    "paths": [],
    "paths_version": 1
  },
  "requested_spec": "defaults/win-64::anaconda-cloud-auth==0.5.1=py312haa95532_0[md5=ce2b46fb864fa7878e37daad5532b1f4]",
  "sha256": "0a18352341bf81d149a1ab2045ce40e87143e647e1d64d69607b31dcabc1eab1",
  "size": 50499,
  "subdir": "win-64",
  "timestamp": 1713991499000,
  "url": "https://repo.anaconda.com/pkgs/main/win-64/anaconda-cloud-auth-0.5.1-py312haa95532_0.conda",
  "version": "0.5.1"
}